"""add users table

Revision ID: 061e810abc38
Revises: cbc335adce4f
Create Date: 2026-07-21 00:47:19.550390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061e810abc38'
down_revision = 'cbc335adce4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_password_reset_tokens_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_password_reset_tokens_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('import_previews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_import_previews_created_by_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_import_previews_created_by_id', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('regulatory_tariffs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_regulatory_tariffs_created_by_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_regulatory_tariffs_created_by_id', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
