"""add faturas

Revision ID: ae38ae40f4a9
Revises: c9190fb66b9f
Create Date: 2026-08-23 23:30:44.969194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae38ae40f4a9'
down_revision = 'c9190fb66b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('consumer_unit_id', sa.Integer(), nullable=True),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_cobrado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('asaas_customer_id', sa.String(length=50), nullable=True),
    sa.Column('asaas_charge_id', sa.String(length=50), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('link_pagamento', sa.String(length=500), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['consumer_unit_id'], ['consumer_units.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturas_asaas_charge_id'), ['asaas_charge_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_faturas_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_faturas_asaas_charge_id'))

    op.drop_table('faturas')
    # ### end Alembic commands ###
