"""add business fields to client uc plant

Revision ID: c4b5632aaedd
Revises: 061e810abc38
Create Date: 2026-07-22 21:54:54.440003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b5632aaedd'
down_revision = '061e810abc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    with op.batch_alter_table('consumer_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_aneel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('documento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('concessionaria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('geracao_propria', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('dia_emissao_fatura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inicio_contrato', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('termino_contrato', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('carencia_meses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('percentual_desconto_carencia', sa.String(length=10), nullable=True))

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_inversor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefone_proprietario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_proprietario', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('email_proprietario')
        batch_op.drop_column('telefone_proprietario')
        batch_op.drop_column('marca_inversor')

    with op.batch_alter_table('consumer_units', schema=None) as batch_op:
        batch_op.drop_column('percentual_desconto_carencia')
        batch_op.drop_column('carencia_meses')
        batch_op.drop_column('termino_contrato')
        batch_op.drop_column('inicio_contrato')
        batch_op.drop_column('dia_emissao_fatura')
        batch_op.drop_column('geracao_propria')
        batch_op.drop_column('concessionaria')
        batch_op.drop_column('cep')
        batch_op.drop_column('endereco')
        batch_op.drop_column('documento')
        batch_op.drop_column('codigo_aneel')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
