"""add password reset tokens

Revision ID: e33e0dc271c4
Revises: a3c8e1f5b9d2
Create Date: 2026-08-19 08:58:55.671382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33e0dc271c4'
down_revision = 'a3c8e1f5b9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('google_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_accounts_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('rateio_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rateio_historico_competencia'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_empresa_id'))

    with op.batch_alter_table('rateio_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rateio_historico_competencia'), ['competencia'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_empresa_id'))

    with op.batch_alter_table('google_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_accounts_empresa_id'))

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
